AircraftDb = [
    {
        "class_name": "F-35B Lightning II",
        "speed": 1043,  # mph
        "max_fuel": 13500,  # lbs
        "fuel_rate": 1100,  # gallons per hour
        "range": 900,  # nm
    },
    {
        "class_name": "KC-135R Stratotanker",
        "speed": 530,
        "max_fuel": 200000,
        "fuel_rate": 15000,
        "range": 1500,
    },
    {
        "class_name": "A-10 Thunderbolt II",
        "speed": 439,
        "max_fuel": 11000,
        "fuel_rate": 800,
        "range": 800,
    },
    {
        "class_name": "B-2 Spirit",
        "speed": 628,
        "max_fuel": 167000,
        "fuel_rate": 10000,
        "range": 6000,
    },
    {
        "class_name": "F-22 Raptor",
        "speed": 1500,
        "max_fuel": 18000,
        "fuel_rate": 1000,
        "range": 1839,
    },
    {
        "class_name": "C-130 Hercules",
        "speed": 366,
        "max_fuel": 61360,
        "fuel_rate": 1100,
        "range": 2361,
    },
    {
        "class_name": "C-17 Globemaster III",
        "speed": 518,
        "max_fuel": 181054,
        "fuel_rate": 20000,
        "range": 2785,
    },
    {
        "class_name": "F-16 Fighting Falcon",
        "speed": 1500,
        "max_fuel": 7000,
        "fuel_rate": 800,
        "range": 2002,
    },
    {
        "class_name": "F-15 Eagle",
        "speed": 1875,
        "max_fuel": 13455,
        "fuel_rate": 1200,
        "range": 3450,
    },
    {
        "class_name": "F/A-18 Hornet",
        "speed": 1190,
        "max_fuel": 14400,
        "fuel_rate": 1250,
        "range": 1250,
    },
    {
        "class_name": "E-3 Sentry (AWACS)",
        "speed": 530,
        "max_fuel": 90000,
        "fuel_rate": 5000,
        "range": 4000,
    },
    {
        "class_name": "B-52 Stratofortress",
        "speed": 650,
        "max_fuel": 312197,
        "fuel_rate": 15000,
        "range": 8800,
    },
    {
        "class_name": "P-8 Poseidon",
        "speed": 564,
        "max_fuel": 34080,
        "fuel_rate": 1000,
        "range": 1200,
    },
    {
        "class_name": "MQ-9 Reaper",
        "speed": 300,
        "max_fuel": 4000,
        "fuel_rate": 200,
        "range": 1150,
    },
    {
        "class_name": "RQ-4 Global Hawk",
        "speed": 391,
        "max_fuel": 17300,
        "fuel_rate": 700,
        "range": 12300,
    },
    {
        "class_name": "CH-47 Chinook",
        "speed": 196,
        "max_fuel": 1068,
        "fuel_rate": 514,
        "range": 400,
    },
    {
        "class_name": "AH-64 Apache",
        "speed": 182,
        "max_fuel": 375,
        "fuel_rate": 150,
        "range": 300,
    },
    {
        "class_name": "UH-60 Black Hawk",
        "speed": 183,
        "max_fuel": 360,
        "fuel_rate": 150,
        "range": 320,
    },
    {
        "class_name": "V-22 Osprey",
        "speed": 277,
        "max_fuel": 12000,
        "fuel_rate": 2400,
        "range": 879,
    },
    {
        "class_name": "MQ-1 Predator",
        "speed": 135,
        "max_fuel": 665,
        "fuel_rate": 100,
        "range": 675,
    },
    {
        "class_name": "AV-8B Harrier II",
        "speed": 662,
        "max_fuel": 7500,
        "fuel_rate": 1200,
        "range": 1000,
    },
    {
        "class_name": "EA-18G Growler",
        "speed": 1190,
        "max_fuel": 14400,
        "fuel_rate": 1250,
        "range": 1200,
    },
    {
        "class_name": "T-38 Talon",
        "speed": 812,
        "max_fuel": 2067,
        "fuel_rate": 600,
        "range": 1093,
    },
    {
        "class_name": "KC-10 Extender",
        "speed": 600,
        "max_fuel": 356000,
        "fuel_rate": 20000,
        "range": 4400,
    },
    {
        "class_name": "P-3 Orion",
        "speed": 411,
        "max_fuel": 60000,
        "fuel_rate": 1000,
        "range": 2380,
    },
    {
        "class_name": "F-4 Phantom II",
        "speed": 1473,
        "max_fuel": 13890,
        "fuel_rate": 1200,
        "range": 1750,
    },
    {
        "class_name": "E-2 Hawkeye",
        "speed": 350,
        "max_fuel": 14280,
        "fuel_rate": 500,
        "range": 1462,
    },
    {
        "class_name": "C-5 Galaxy",
        "speed": 518,
        "max_fuel": 332500,
        "fuel_rate": 20000,
        "range": 5200,
    },
    {
        "class_name": "B-1B Lancer",
        "speed": 900,
        "max_fuel": 265274,
        "fuel_rate": 18000,
        "range": 5100,
    },
    {
        "class_name": "C-141 Starlifter",
        "speed": 500,
        "max_fuel": 116000,
        "fuel_rate": 10000,
        "range": 4000,
    },
    {
        "class_name": "E-8 Joint STARS",
        "speed": 530,
        "max_fuel": 160000,
        "fuel_rate": 7000,
        "range": 9000,
    },
    {
        "class_name": "B-47 Stratojet",
        "speed": 607,
        "max_fuel": 53000,
        "fuel_rate": 6000,
        "range": 4000,
    },
    {
        "class_name": "F-117 Nighthawk",
        "speed": 617,
        "max_fuel": 19000,
        "fuel_rate": 1300,
        "range": 1070,
    },
    {
        "class_name": "SR-71 Blackbird",
        "speed": 2193,
        "max_fuel": 80000,
        "fuel_rate": 8000,
        "range": 3200,
    },
    {
        "class_name": "U-2 Dragon Lady",
        "speed": 475,
        "max_fuel": 7750,
        "fuel_rate": 500,
        "range": 7000,
    },
    {
        "class_name": "AC-130 Gunship",
        "speed": 300,
        "max_fuel": 60000,
        "fuel_rate": 1200,
        "range": 1300,
    },
    {
        "class_name": "HH-60 Pave Hawk",
        "speed": 184,
        "max_fuel": 360,
        "fuel_rate": 150,
        "range": 600,
    },
    {
        "class_name": "KC-46 Pegasus",
        "speed": 570,
        "max_fuel": 212299,
        "fuel_rate": 10000,
        "range": 6385,
    },
    {
        "class_name": "T-6 Texan II",
        "speed": 364,
        "max_fuel": 2826,
        "fuel_rate": 250,
        "range": 1037,
    },
    {
        "class_name": "RQ-7 Shadow",
        "speed": 138,
        "max_fuel": 110,
        "fuel_rate": 10,
        "range": 68,
    },
    {
        "class_name": "C-12 Huron",
        "speed": 333,
        "max_fuel": 5890,
        "fuel_rate": 300,
        "range": 2290,
    },
    {
        "class_name": "T-1 Jayhawk",
        "speed": 538,
        "max_fuel": 6000,
        "fuel_rate": 450,
        "range": 2222,
    },
    {
        "class_name": "EC-130H Compass Call",
        "speed": 299,
        "max_fuel": 60000,
        "fuel_rate": 1200,
        "range": 2295,
    },
    {
        "class_name": "OV-10 Bronco",
        "speed": 288,
        "max_fuel": 3120,
        "fuel_rate": 250,
        "range": 1240,
    },
    {
        "class_name": "C-21A Learjet",
        "speed": 530,
        "max_fuel": 6000,
        "fuel_rate": 600,
        "range": 2306,
    },
    {
        "class_name": "T-45 Goshawk",
        "speed": 645,
        "max_fuel": 3255,
        "fuel_rate": 500,
        "range": 900,
    },
    {
        "class_name": "A-6 Intruder",
        "speed": 644,
        "max_fuel": 30400,
        "fuel_rate": 1200,
        "range": 2000,
    },
    {
        "class_name": "F-14 Tomcat",
        "speed": 1544,
        "max_fuel": 16200,
        "fuel_rate": 1800,
        "range": 1600,
    },
    {
        "class_name": "F-8 Crusader",
        "speed": 1225,
        "max_fuel": 9266,
        "fuel_rate": 1200,
        "range": 1450,
    },
    {
        "class_name": "B-29 Superfortress",
        "speed": 357,
        "max_fuel": 20000,
        "fuel_rate": 1000,
        "range": 3250,
    },
]

AirbaseDb = [
    {
        "name": "Al Udeid Air Base",
        "latitude": 25.1175,
        "longitude": 51.315,
        "country": "Qatar",
    },
    {
        "name": "Andersen Air Force Base",
        "latitude": 13.5841,
        "longitude": 144.9245,
        "country": "Guam",
    },
    {
        "name": "Andrews Air Force Base",
        "latitude": 38.8108,
        "longitude": -76.866,
        "country": "USA",
    },
    {
        "name": "Aviano Air Base",
        "latitude": 46.0319,
        "longitude": 12.5965,
        "country": "Italy",
    },
    {
        "name": "Bagram Airfield",
        "latitude": 34.9462,
        "longitude": 69.265,
        "country": "Afghanistan",
    },
    {
        "name": "Beale Air Force Base",
        "latitude": 39.1236,
        "longitude": -121.4368,
        "country": "USA",
    },
    {
        "name": "Creech Air Force Base",
        "latitude": 36.5822,
        "longitude": -115.6711,
        "country": "USA",
    },
    {
        "name": "Davis-Monthan Air Force Base",
        "latitude": 32.1665,
        "longitude": -110.883,
        "country": "USA",
    },
    {
        "name": "Eglin Air Force Base",
        "latitude": 30.4833,
        "longitude": -86.5254,
        "country": "USA",
    },
    {
        "name": "Edwards Air Force Base",
        "latitude": 34.9054,
        "longitude": -117.8839,
        "country": "USA",
    },
    {
        "name": "Elmendorf Air Force Base",
        "latitude": 61.25,
        "longitude": -149.8,
        "country": "USA",
    },
    {
        "name": "Elmendorf-Richardson",
        "latitude": 61.254,
        "longitude": -149.792,
        "country": "USA",
    },
    {
        "name": "Hickam Air Force Base",
        "latitude": 21.3169,
        "longitude": -157.9334,
        "country": "USA",
    },
    {
        "name": "Incirlik Air Base",
        "latitude": 37.0017,
        "longitude": 35.4251,
        "country": "Turkey",
    },
    {
        "name": "Joint Base Pearl Harbor-Hickam",
        "latitude": 21.3469,
        "longitude": -157.9397,
        "country": "USA",
    },
    {
        "name": "Kadena Air Base",
        "latitude": 26.3516,
        "longitude": 127.7692,
        "country": "Japan",
    },
    {
        "name": "Kunsan Air Base",
        "latitude": 35.9023,
        "longitude": 126.615,
        "country": "South Korea",
    },
    {
        "name": "Lackland Air Force Base",
        "latitude": 29.3842,
        "longitude": -98.5811,
        "country": "USA",
    },
    {
        "name": "Luke Air Force Base",
        "latitude": 33.5386,
        "longitude": -112.358,
        "country": "USA",
    },
    {
        "name": "Marine Corps Air Station Cherry Point",
        "latitude": 34.9008,
        "longitude": -76.88,
        "country": "USA",
    },
    {
        "name": "Marine Corps Air Station Iwakuni",
        "latitude": 34.1463,
        "longitude": 132.2365,
        "country": "Japan",
    },
    {
        "name": "Marine Corps Air Station Miramar",
        "latitude": 32.8683,
        "longitude": -117.1424,
        "country": "USA",
    },
    {
        "name": "Marine Corps Base Camp Pendleton",
        "latitude": 33.3852,
        "longitude": -117.565,
        "country": "USA",
    },
    {
        "name": "McChord Air Force Base",
        "latitude": 47.137,
        "longitude": -122.4745,
        "country": "USA",
    },
    {
        "name": "Minot Air Force Base",
        "latitude": 48.4159,
        "longitude": -101.3306,
        "country": "USA",
    },
    {
        "name": "Misawa Air Base",
        "latitude": 40.7032,
        "longitude": 141.3686,
        "country": "Japan",
    },
    {
        "name": "Moody Air Force Base",
        "latitude": 30.9674,
        "longitude": -83.193,
        "country": "USA",
    },
    {
        "name": "Nellis Air Force Base",
        "latitude": 36.236,
        "longitude": -115.034,
        "country": "USA",
    },
    {
        "name": "Naval Air Facility Atsugi",
        "latitude": 35.4542,
        "longitude": 139.4493,
        "country": "Japan",
    },
    {
        "name": "Naval Air Station Fallon",
        "latitude": 39.4169,
        "longitude": -118.7002,
        "country": "USA",
    },
    {
        "name": "Naval Air Station Jacksonville",
        "latitude": 30.2358,
        "longitude": -81.6806,
        "country": "USA",
    },
    {
        "name": "Naval Air Station Oceana",
        "latitude": 36.8206,
        "longitude": -76.0331,
        "country": "USA",
    },
    {
        "name": "Naval Air Station Patuxent River",
        "latitude": 38.2851,
        "longitude": -76.4112,
        "country": "USA",
    },
    {
        "name": "Naval Air Station Pensacola",
        "latitude": 30.3501,
        "longitude": -87.3095,
        "country": "USA",
    },
    {
        "name": "Naval Air Station Sigonella",
        "latitude": 37.4017,
        "longitude": 14.9222,
        "country": "Italy",
    },
    {
        "name": "Naval Air Station Whidbey Island",
        "latitude": 48.3516,
        "longitude": -122.6551,
        "country": "USA",
    },
    {
        "name": "Naval Station Rota",
        "latitude": 36.6414,
        "longitude": -6.3497,
        "country": "Spain",
    },
    {
        "name": "Osan Air Base",
        "latitude": 37.0901,
        "longitude": 127.0305,
        "country": "South Korea",
    },
    {
        "name": "Patrick Air Force Base",
        "latitude": 28.2346,
        "longitude": -80.6101,
        "country": "USA",
    },
    {
        "name": "RAF Fairford",
        "latitude": 51.682,
        "longitude": -1.79,
        "country": "United Kingdom",
    },
    {
        "name": "RAF Lakenheath",
        "latitude": 52.4093,
        "longitude": 0.5616,
        "country": "United Kingdom",
    },
    {
        "name": "RAF Mildenhall",
        "latitude": 52.3611,
        "longitude": 0.4864,
        "country": "United Kingdom",
    },
    {
        "name": "Ramstein Air Base",
        "latitude": 49.4369,
        "longitude": 7.6003,
        "country": "Germany",
    },
    {
        "name": "Royal Australian Air Force Base Amberley",
        "latitude": -27.637,
        "longitude": 152.711,
        "country": "Australia",
    },
    {
        "name": "Seymour Johnson Air Force Base",
        "latitude": 35.3394,
        "longitude": -77.9606,
        "country": "USA",
    },
    {
        "name": "Spangdahlem Air Base",
        "latitude": 49.9725,
        "longitude": 6.6925,
        "country": "Germany",
    },
    {
        "name": "Thule Air Base",
        "latitude": 76.5312,
        "longitude": -68.7031,
        "country": "Greenland",
    },
    {
        "name": "Travis Air Force Base",
        "latitude": 38.2626,
        "longitude": -121.9275,
        "country": "USA",
    },
    {
        "name": "Tyndall Air Force Base",
        "latitude": 30.0696,
        "longitude": -85.6069,
        "country": "USA",
    },
    {
        "name": "Whiteman Air Force Base",
        "latitude": 38.7267,
        "longitude": -93.5479,
        "country": "USA",
    },
]

FacilityDb = [
    {
        "class_name": "9K330 Tor",
        "range": 6.5,
    },
    {
        "class_name": "9K37 Buk",
        "range": 22.7,
    },
    {
        "class_name": "Arrow 2",
        "range": 48.6,
    },
    {
        "class_name": "Arrow 3",
        "range": 1296,
    },
    {
        "class_name": "Aster 15",
        "range": 16.2,
    },
    {
        "class_name": "Aster 30",
        "range": 64.8,
    },
    {
        "class_name": "Barak 1",
        "range": 6.5,
    },
    {
        "class_name": "Barak 8",
        "range": 37.8,
    },
    {
        "class_name": "Buk-M2",
        "range": 27,
    },
    {
        "class_name": "Buk-M3",
        "range": 37.8,
    },
    {
        "class_name": "CAMM",
        "range": 13.5,
    },
    {
        "class_name": "Crotale",
        "range": 5.4,
    },
    {
        "class_name": "David's Sling",
        "range": 162,
    },
    {
        "class_name": "FD-2000",
        "range": 108,
    },
    {
        "class_name": "HQ-16",
        "range": 21.6,
    },
    {
        "class_name": "HQ-22",
        "range": 91.8,
    },
    {
        "class_name": "HQ-9",
        "range": 108,
    },
    {
        "class_name": "Iron Dome",
        "range": 37.8,
    },
    {
        "class_name": "KS-1A",
        "range": 27,
    },
    {
        "class_name": "KS-1C",
        "range": 37.8,
    },
    {
        "class_name": "LY-80",
        "range": 21.6,
    },
    {
        "class_name": "MIM-104 Patriot",
        "range": 86.4,
    },
    {
        "class_name": "NASAMS",
        "range": 13.5,
    },
    {
        "class_name": "NASAMS 2",
        "range": 16.2,
    },
    {
        "class_name": "Pantsir-S1",
        "range": 10.8,
    },
    {
        "class_name": "QRSAM",
        "range": 16.2,
    },
    {
        "class_name": "RIM-116 Rolling Airframe Missile",
        "range": 5.4,
    },
    {
        "class_name": "RIM-162 ESSM",
        "range": 27,
    },
    {
        "class_name": "RIM-174 ERAM (SM-6)",
        "range": 129.6,
    },
    {
        "class_name": "RIM-7 Sea Sparrow",
        "range": 10.3,
    },
    {
        "class_name": "S-125 Neva/Pechora",
        "range": 18.9,
    },
    {
        "class_name": "S-200 Angara",
        "range": 162,
    },
    {
        "class_name": "S-300",
        "range": 108,
    },
    {
        "class_name": "S-350E Vityaz",
        "range": 32.4,
    },
    {
        "class_name": "S-400",
        "range": 216,
    },
    {
        "class_name": "S-75 Dvina",
        "range": 24.3,
    },
    {
        "class_name": "SA-15 Gauntlet",
        "range": 6.5,
    },
    {
        "class_name": "SA-8 Gecko",
        "range": 6.5,
    },
    {
        "class_name": "SAMP/T",
        "range": 64.8,
    },
    {
        "class_name": "Sky Bow II",
        "range": 108,
    },
    {
        "class_name": "Skyguard Aspide",
        "range": 10.8,
    },
    {
        "class_name": "SPYDER",
        "range": 18.9,
    },
    {
        "class_name": "Standard Missile 2 (SM-2)",
        "range": 91.8,
    },
    {
        "class_name": "THAAD",
        "range": 108,
    },
    {
        "class_name": "Type 03 Chū-SAM",
        "range": 27,
    },
    {
        "class_name": "Umkhonto",
        "range": 6.5,
    },
    {
        "class_name": "VL MICA",
        "range": 10.8,
    },
    {
        "class_name": "Vityaz",
        "range": 32.4,
    },
    {
        "class_name": "ZRK-SD Kub",
        "range": 13,
    },
]

ShipDb = [
    {
        "class_name": "Admiral Gorshkov Frigate",
        "speed": 30,
        "max_fuel": 410000,
        "fuel_rate": 3000,
        "range": 4500,
    },
    {
        "class_name": "Admiral Grigorovich Frigate",
        "speed": 30,
        "max_fuel": 400000,
        "fuel_rate": 3000,
        "range": 4850,
    },
    {
        "class_name": "Akizuki Destroyer",
        "speed": 30,
        "max_fuel": 460000,
        "fuel_rate": 3500,
        "range": 5000,
    },
    {
        "class_name": "Alvaro de Bazan Frigate",
        "speed": 28,
        "max_fuel": 370000,
        "fuel_rate": 2800,
        "range": 4500,
    },
    {
        "class_name": "Arleigh Burke Destroyer",
        "speed": 30,
        "max_fuel": 400000,
        "fuel_rate": 4000,
        "range": 4500,
    },
    {
        "class_name": "Atago Destroyer",
        "speed": 30,
        "max_fuel": 500000,
        "fuel_rate": 4000,
        "range": 5000,
    },
    {
        "class_name": "Borei Submarine",
        "speed": 25,
        "max_fuel": 150000,
        "fuel_rate": 500,
        "range": 8000,
    },
    {
        "class_name": "Charles de Gaulle Aircraft Carrier",
        "speed": 27,
        "max_fuel": 1800000,
        "fuel_rate": 12000,
        "range": 8000,
    },
    {
        "class_name": "Chengdu Destroyer",
        "speed": 30,
        "max_fuel": 460000,
        "fuel_rate": 3000,
        "range": 4500,
    },
    {
        "class_name": "Columbia Submarine",
        "speed": 20,
        "max_fuel": 160000,
        "fuel_rate": 500,
        "range": 8000,
    },
    {
        "class_name": "Daring Destroyer",
        "speed": 29,
        "max_fuel": 500000,
        "fuel_rate": 3500,
        "range": 7000,
    },
    {
        "class_name": "De Zeven Provinciën Frigate",
        "speed": 28,
        "max_fuel": 400000,
        "fuel_rate": 3000,
        "range": 5000,
    },
    {
        "class_name": "Freedom Littoral Combat Ship",
        "speed": 45,
        "max_fuel": 310000,
        "fuel_rate": 3500,
        "range": 3500,
    },
    {
        "class_name": "Gerald R. Ford Aircraft Carrier",
        "speed": 30,
        "max_fuel": 3000000,
        "fuel_rate": 15000,
        "range": 12000,
    },
    {
        "class_name": "Hobart Destroyer",
        "speed": 28,
        "max_fuel": 400000,
        "fuel_rate": 3000,
        "range": 4500,
    },
    {
        "class_name": "Horizon Frigate",
        "speed": 29,
        "max_fuel": 480000,
        "fuel_rate": 3000,
        "range": 7000,
    },
    {
        "class_name": "Iowa Battleship",
        "speed": 33,
        "max_fuel": 2000000,
        "fuel_rate": 15000,
        "range": 15000,
    },
    {
        "class_name": "Invincible Aircraft Carrier",
        "speed": 28,
        "max_fuel": 1000000,
        "fuel_rate": 8000,
        "range": 7000,
    },
    {
        "class_name": "Iver Huitfeldt Frigate",
        "speed": 28,
        "max_fuel": 450000,
        "fuel_rate": 3200,
        "range": 9000,
    },
    {
        "class_name": "Kidd Destroyer",
        "speed": 33,
        "max_fuel": 400000,
        "fuel_rate": 4000,
        "range": 6000,
    },
    {
        "class_name": "Kirov Battle Cruiser",
        "speed": 32,
        "max_fuel": 3000000,
        "fuel_rate": 12000,
        "range": 10000,
    },
    {
        "class_name": "King Sejong the Great Destroyer",
        "speed": 30,
        "max_fuel": 550000,
        "fuel_rate": 5000,
        "range": 5000,
    },
    {
        "class_name": "Kirov Cruiser",
        "speed": 32,
        "max_fuel": 3000000,
        "fuel_rate": 15000,
        "range": 10000,
    },
    {
        "class_name": "Lafayette Frigate",
        "speed": 25,
        "max_fuel": 400000,
        "fuel_rate": 3000,
        "range": 9000,
    },
    {
        "class_name": "Littoral Combat Ship",
        "speed": 45,
        "max_fuel": 310000,
        "fuel_rate": 3500,
        "range": 3500,
    },
    {
        "class_name": "Nimitz Aircraft Carrier",
        "speed": 30,
        "max_fuel": 3000000,
        "fuel_rate": 15000,
        "range": 12000,
    },
    {
        "class_name": "Ohio Submarine",
        "speed": 25,
        "max_fuel": 150000,
        "fuel_rate": 500,
        "range": 8000,
    },
    {
        "class_name": "Oliver Hazard Perry Frigate",
        "speed": 29,
        "max_fuel": 353000,
        "fuel_rate": 2500,
        "range": 4500,
    },
    {
        "class_name": "Osprey Minehunter",
        "speed": 12,
        "max_fuel": 100000,
        "fuel_rate": 1500,
        "range": 1500,
    },
    {
        "class_name": "Queen Elizabeth Aircraft Carrier",
        "speed": 25,
        "max_fuel": 3000000,
        "fuel_rate": 12000,
        "range": 10000,
    },
    {
        "class_name": "Seawolf Submarine",
        "speed": 25,
        "max_fuel": 150000,
        "fuel_rate": 500,
        "range": 8000,
    },
    {
        "class_name": "Sierra Submarine",
        "speed": 32,
        "max_fuel": 150000,
        "fuel_rate": 500,
        "range": 7200,
    },
    {
        "class_name": "Slava Cruiser",
        "speed": 32,
        "max_fuel": 2000000,
        "fuel_rate": 8000,
        "range": 10000,
    },
    {
        "class_name": "Sovereign Submarine",
        "speed": 25,
        "max_fuel": 150000,
        "fuel_rate": 500,
        "range": 8000,
    },
    {
        "class_name": "Ticonderoga Cruiser",
        "speed": 32,
        "max_fuel": 500000,
        "fuel_rate": 4500,
        "range": 6000,
    },
    {
        "class_name": "Type 055 Destroyer",
        "speed": 30,
        "max_fuel": 600000,
        "fuel_rate": 4000,
        "range": 6000,
    },
    {
        "class_name": "Type 23 Frigate",
        "speed": 28,
        "max_fuel": 450000,
        "fuel_rate": 3000,
        "range": 7500,
    },
    {
        "class_name": "Type 45 Destroyer",
        "speed": 30,
        "max_fuel": 400000,
        "fuel_rate": 3500,
        "range": 7000,
    },
    {
        "class_name": "Type 52D Destroyer",
        "speed": 30,
        "max_fuel": 460000,
        "fuel_rate": 3500,
        "range": 4500,
    },
    {
        "class_name": "Udaloy Destroyer",
        "speed": 35,
        "max_fuel": 400000,
        "fuel_rate": 4000,
        "range": 9000,
    },
    {
        "class_name": "Zumwalt Destroyer",
        "speed": 30,
        "max_fuel": 500000,
        "fuel_rate": 4500,
        "range": 6000,
    },
]
